url: https://hen-son.github.io/dig-geo/
baseurl: "https://hen-son.github.io/dig-geo/"
title: Digitale Geographien
email: kontakt@digitale-geographien.de

description: Ein deutschsprachiges Forschungsnetzwerk zu Geodaten, Code und Gesellschaft

navbar-links:
  Netzwerk: "netzwerk"
  Mitglieder: "mitglieder"
  Publikationen: "publikationen"

avatar: "/bilder/logo_big.png"

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

author:
  name: Netzwerk Digitale Geographien

social-network-links:
  rss: true
  email: "kontakt@digitale-geographien.de"

share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: false

url-pretty: "digitale-geographien.de"  # eg. "deanattali.com/beautiful-jekyll"

excerpt_length: 50
title-separator: "-"

timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

link-tags: true

include: ['_pages']

exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

plugins:
  - jekyll-paginate
  - jekyll-sitemap
